name: Build chip-tool

on:
  push:
    branches:
      - chip-tool-ci
    tags:
      - 'v*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
  cancel-in-progress: true


jobs:
  chip_tool:
    name: chip_tool
    runs-on: ubuntu-latest
    if: github.actor != 'restyled-io[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Check code path
        run: |
          echo ls && \
          echo pwd
      - name: Build
        run: |
          source scripts/activate.sh && \
          gn gen out/host && \
          ninja -C out/host chip-cert && \
          echo ls out/host
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chip-tool
          path: ./out/host/chip-cert