# Copyright (c) 2022-2024 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build example - Telink

on:
  push:
    branches:
      - dual_mode_develop_ci
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
  cancel-in-progress: true

env:
  CHIP_NO_LOG_TIMESTAMPS: true

jobs:
  telink:
    name: Telink
    env:
      BUILD_TYPE: telink

    runs-on: ubuntu-20.04
    if: github.actor != 'restyled-io[bot]'

    container:
      image: ghcr.io/project-chip/chip-build-telink:66
      volumes:
        - "/tmp/bloat_reports:/tmp/bloat_reports"
        - "/tmp/telink_build_artifacts:/tmp/telink_build_artifacts"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodules & Bootstrap
        uses: ./.github/actions/checkout-submodules-and-bootstrap
        with:
          platform: telink

      - name: Set up environment for size reports
        uses: ./.github/actions/setup-size-reports
        if: ${{ !env.ACT }}
        with:
          gh-context: ${{ toJson(github) }}

      - name: Update Zephyr to specific revision (for developers purpose)
        run: |
          scripts/run_in_build_env.sh \
            "python3 scripts/tools/telink/update_zephyr.py \
            5a5825a19080d27f36adb23f32d9c05e528fa14c \
            https://github.com/damien0x0023/zephyr"

      - name: Build example Telink (B92) Lighting App with OTA and 4Mb flash
        run: |
          ./scripts/run_in_build_env.sh \
            "./scripts/build/build_examples.py --target 'telink-tlsr9528a-light-ota-4mb' build"
          .environment/pigweed-venv/bin/python3 scripts/tools/memory/gh_sizes.py \
            telink tlsr9528a lighting-app-ota-4mb \
            out/telink-tlsr9528a-light-ota-4mb/zephyr/zephyr.elf \
            /tmp/bloat_reports/
          cp out/telink-tlsr9528a-light-ota-4mb/zephyr/zephyr.bin \
            /tmp/telink_build_artifacts/telink-tlsr9528a-light-ota-4mb.bin
          echo "=============test============"
          cat /tmp/telink_build_artifacts/telink-tlsr9528a-light-ota-4mb.bin

      - name: clean out build output
        run: rm -rf ./out

      - name: Uploading Size Reports
        uses: ./.github/actions/upload-size-reports
        if: ${{ !env.ACT }}
        with:
          platform-name: Telink

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: telink-examples,${{ github.event_name }}
          path: |
            /tmp/telink_build_artifacts/*
