# Copyright (c) 2026 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build example - TI CC27XX

on:
    workflow_dispatch:
    push:
        branches:
            - ti-cc2745

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_NO_LOG_TIMESTAMPS: true

jobs:
    cc27xx:
        name: cc27xx

        env:
            BUILD_TYPE: gn_cc27xx

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: ghcr.io/project-chip/chip-build-ti:81
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                  platform: cc27xx
                  extra-submodule-parameters: " --recursive"

            - name: Install TI SysConfig
              shell: bash
              run: |
                  if [ ! -d /opt/ti/sysconfig_1.23.2 ]; then
                      wget https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-nsUM6f7Vvb/1.23.2.4156/sysconfig-1.23.2_4156-setup.run
                      chmod +x sysconfig-1.23.2_4156-setup.run
                      ./sysconfig-1.23.2_4156-setup.run --mode unattended
                  fi
                  echo "TI_SYSCONFIG_ROOT=/opt/ti/sysconfig_1.23.2" >> "$GITHUB_ENV"

            - name: Build examples
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target ti-cc27xx-lock-ftd \
                      build \
                      --copy-artifacts-to out/artifacts \
                  "

            - name: Uploading build artifacts
              uses: actions/upload-artifact@v4
              if: ${{ !env.ACT }}
              with:
                  name: cc27xx-lock
                  path: out/artifacts/ti-cc27xx-lock-ftd/
